Updates + HTTP Client Sanity
ParadiseSS13/rust-g-old pull request #4
Opened 2020-10-29 00:09 UTC by AffectedArc07

This PR imports some more updates from TG, as well as new methods for the HTTP client to manually create and close the thread pools.

This is quite possibly, the worst code I have ever written. But it does work.

Closing an already closed pool does not break
Opening an already open pool does not break
Making web requests on a closed pool does not break (It just does nothing)

Logging still works
![image](https://user-images.githubusercontent.com/25063394/97509701-eb573e80-197a-11eb-8cbc-2b9a2fd506fa.png)

2020-10-29 12:19 UTC, spookydonut requested changes
fix your editor

2020-10-29 12:19 UTC, spookydonut commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
you cant use comments in a json

2020-10-29 12:19 UTC, spookydonut commented on src/dmi.rs
> +}
newline

2020-10-29 12:19 UTC, spookydonut commented on src/http.rs
> +} }
newline

2020-10-29 12:19 UTC, spookydonut commented on src/sql.rs
> +}
newline

2020-10-29 12:19 UTC, spookydonut commented on src/url.rs
> +}
newline

2020-10-29 12:25 UTC, AffectedArc07 commented
Force pushed to uncommit my `launch.json`

2020-10-29 14:36 UTC, aspenluxxxy approved these changes
lgtm

2020-10-29 20:50 UTC, Putnam3145 commented on Cargo.toml
> +lazy_static = { version = "1.4", optional = true }
probably don't need this anymore since you're not using it from what i can see

2020-10-29 21:01 UTC, AffectedArc07 commented on Cargo.toml
> +lazy_static = { version = "1.4", optional = true }
Resolved

2020-10-31 21:00 UTC, Nukeuler123 approved these changes
All of this looks good, even though my IDE is complaining about some error everything compiles just fine.

2020-10-31 22:06 UTC, merged